version: 2

project_name: dhcli

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  # Default: ZIP per tutti
  - formats: [zip]
    # name template compatibile con `uname`
    name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "windows" }}windows
      {{- else if eq .Os "darwin" }}darwin
      {{- else if eq .Os "linux" }}linux
      {{- else }}{{ .Os }}{{ end }}
      {{- if eq .Arch "all" }}
      {{- else }}-{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Override: su darwin usa tar.gz
    format_overrides:
      - goos: darwin
        formats: [tar.gz]

universal_binaries:
  - replace: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  replace_existing_draft: true
  replace_existing_artifacts: true

brews:
  - repository:
      owner: scc-digitalhub
      name: digitalhub-cli
    directory: Formula
    homepage: https://scc-digitalhub.github.io/
    description: A command-line tool for DigitalHub platform.
