version: 2

project_name: dhcli

builds:
  - id: dhcli
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    # (optional) main: ./cmd/dhcli

archives:
  # ZIP for all targets
  - id: zip
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "windows" }}windows{{ else if eq .Os "darwin" }}darwin{{ else if eq .Os "linux" }}linux{{ else }}{{ .Os }}{{ end }}
      {{- if ne .Arch "all" }}-{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # TAR.GZ for all targets
  - id: tgz
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "windows" }}windows{{ else if eq .Os "darwin" }}darwin{{ else if eq .Os "linux" }}linux{{ else }}{{ .Os }}{{ end }}
      {{- if ne .Arch "all" }}-{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

universal_binaries:
  - id: dhcli-universal
    # will merge darwin/amd64 + darwin/arm64 from build "dhcli"
    replace: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  replace_existing_draft: true
  replace_existing_artifacts: true

# NOTE: "brews" is deprecated; you'll see a warning.
# For now, keep it (CLI formula) and pin it to a SINGLE archive id (tgz).
brews:
  - name: dhcli
    ids: [tgz]        # <-- important: pick only one archive set for the formula
    repository:
      owner: scc-digitalhub
      name: digitalhub-cli
    directory: Formula
    homepage: https://scc-digitalhub.github.io/
    description: A command-line tool for DigitalHub platform.
    skip_upload: auto  # skip on pre-releases
