version: 2

project_name: dhcli

builds:
  # General build: all targets
  - id: dhcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  # Brew-only build: darwin targets (kept separate so brew sees a single archive/arch)
  - id: brew
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  # Produce ZIP for the general build
  - id: zip_all
    builds:
      - dhcli
    format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # Produce TGZ for the general build
  - id: tgz_all
    builds:
      - dhcli
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  # Produce a single TGZ per darwin arch for Homebrew (from the 'brew' build only)
  - id: tgz_brew
    builds:
      - brew
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

# Merge darwin/amd64 + darwin/arm64 for the brew build (single universal binary)
universal_binaries:
  - id: brew_universal
    ids:
      - brew
    replace: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  replace_existing_draft: true
  replace_existing_artifacts: true

brews:
  - ids:
      - brew        # only consume artifacts from the 'brew' build
    repository:
      owner: scc-digitalhub
      name: digitalhub-cli
    directory: Formula
    homepage: https://scc-digitalhub.github.io/
    description: A command-line tool for DigitalHub platform.
    skip_upload: auto   # skip on prereleases, publish on stable
