# typed: false
# frozen_string_literal: true

# Generated by .github/workflows/release.yaml. DO NOT EDIT.
class DhcliAT015 < Formula
  desc "A command-line tool for DigitalHub platform."
  homepage "https://scc-digitalhub.github.io/"
  version "0.15.0-beta3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.15.0-beta3/dhcli-darwin-amd64.tar.gz"
      sha256 "8b1caec48e2404130675abf28b74dd10d1d78bc2e45f71d6d69ef13a5aae5c64"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.15.0-beta3/dhcli-darwin-arm64.tar.gz"
      sha256 "9cacbfc15b7b5b82a339639b36cb7517413c77f5c5b90a9a77c098f930740045"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.15.0-beta3/dhcli-linux-amd64.tar.gz"
      sha256 "6da8ec960c10c30f81a908a85eba383a341f9f6df30d688096b51a0e0068b358"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.15.0-beta3/dhcli-linux-arm64.tar.gz"
      sha256 "518da1c4e5cf560f966775e444619d654c16bcd9e75688844d8ddcbea915ec92"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end
end
