# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dhcli < Formula
  desc "A command-line tool for DigitalHub platform."
  homepage "https://scc-digitalhub.github.io/"
  version "0.14.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.3/dhcli-darwin-amd64.tar.gz"
      sha256 "25b37a903d2ef6597662d5bac7d57805771b6666cccf19d6fe18ab1ac52a1875"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.3/dhcli-darwin-arm64.tar.gz"
      sha256 "031a284e4284aec1b41c4a0d5cbb8002d64d0aa5d7048f8097043ec38271a685"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.3/dhcli-linux-amd64.tar.gz"
      sha256 "75b6b31d9dafbc1ecaaeb7f9be4bb9ed7efae2e227f55d86e817d598601e7f80"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.3/dhcli-linux-arm64.tar.gz"
      sha256 "74fa36758bd602d1259f3ed35060704576c148b0e46834cdf4ad48c28095b0c8"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end
end
