# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DhcliAT014 < Formula
  desc "A command-line tool for DigitalHub platform."
  homepage "https://scc-digitalhub.github.io/"
  version "0.14.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-darwin-amd64.tar.gz"
      sha256 "91e0581fdf17a96da027d3e6c207cd76e3883efcacc119ef5c68c188b3bd665c"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-darwin-arm64.tar.gz"
      sha256 "8a64647d520f5ec93885146265777cad1691bb0a03c622e999d62477672b9c7f"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-linux-amd64.tar.gz"
      sha256 "13fb088c0e350b3f025bb0311c011935cacfdb07a329a961b7743cd295580685"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-linux-arm64.tar.gz"
      sha256 "0e99894760c9c4600e0180f6ebb5f1bb2fe5de476916c423f0553222af6e108c"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end
end
