# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DhcliAT014 < Formula
  desc "A command-line tool for DigitalHub platform."
  homepage "https://scc-digitalhub.github.io/"
  version "0.14.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-darwin-amd64.tar.gz"
      sha256 "1b7b7f6251549cd756144ab7416c319f02bc3274dd45a4b5ab72bc503699340c"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-darwin-arm64.tar.gz"
      sha256 "945a4fd3eb992269c2ad679442af4f808b628136ac72f43f317228a7d5a1a7d5"

      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-linux-amd64.tar.gz"
      sha256 "39a647337ea74ff397ba2ead5b16cde79e033485772d689ebf6aaf2d8030cf49"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.14.4/dhcli-linux-arm64.tar.gz"
      sha256 "ac5312315deb34fc0bf4293110a46c26275f54ad499a0338c3550f5cecbcfcb0"
      define_method(:install) do
        bin.install "dhcli"
      end
    end
  end
end
